-- 코드를 입력하세요
SELECT USED_GOODS_USER.USER_ID,NICKNAME,CONCAT(CITY," ",STREET_ADDRESS1," ",STREET_ADDRESS2) AS '전체주소',CONCAT(SUBSTR(TLNO,1,3),"-",SUBSTR(TLNO,4,4),"-",SUBSTR(TLNO,8,4)) AS '전화번호'
FROM USED_GOODS_BOARD
INNER JOIN USED_GOODS_USER ON USED_GOODS_USER.USER_ID=USED_GOODS_BOARD.WRITER_ID
GROUP BY USED_GOODS_BOARD.WRITER_ID
HAVING COUNT(*)>=3
ORDER BY USED_GOODS_BOARD.WRITER_ID DESC