-- 코드를 입력하세요
SELECT A1.CAR_ID,ROUND(AVG(DURATION),1) AS AVERAGE_DURATION
FROM
(SELECT *,DATEDIFF(END_DATE,START_DATE)+1 AS DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) A1
GROUP BY A1.CAR_ID
HAVING AVERAGE_DURATION>=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC