-- 코드를 입력하세요
SELECT A2.PRODUCT_ID,A2.PRODUCT_NAME,SUM(A2.TOTAL_SALES) AS TOTAL_SALES
FROM(

SELECT FOOD_PRODUCT.PRODUCT_ID,PRODUCT_NAME, PRICE*AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT
INNER JOIN FOOD_ORDER ON FOOD_PRODUCT.PRODUCT_ID= FOOD_ORDER.PRODUCT_ID
WHERE MONTH(PRODUCE_DATE) = 5
    ) A2
GROUP BY A2.PRODUCT_ID
ORDER BY TOTAL_SALES DESC , A2.PRODUCT_ID ASC 
    