-- 코드를 입력하세요
SELECT A1.APNT_NO,A1.PT_NAME,A1.PT_NO,A1.MCDP_CD,DR_NAME,A1.APNT_YMD
FROM
(SELECT *
FROM PATIENT
RIGHT JOIN APPOINTMENT USING(PT_NO)
WHERE APNT_YMD LIKE '%2022-04-13%'
)AS A1
LEFT JOIN DOCTOR ON DR_ID= A1.MDDR_ID
WHERE APNT_CNCL_YN ='N' 
ORDER BY A1.APNT_YMD ASC
