-- 코드를 입력하세요
WITH More5Counts AS (
    SELECT CAR_ID, COUNT(*) AS TOTAL_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID,COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN More5Counts B ON A.CAR_ID = B.CAR_ID
WHERE A.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY A.CAR_ID, MONTH(A.START_DATE)
ORDER BY MONTH(A.START_DATE) ASC, A.CAR_ID DESC