-- 코드를 입력하세요
SELECT CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
INNER JOIN CAR_RENTAL_COMPANY_CAR ON CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
WHERE CAR_TYPE LIKE '세단' AND MONTH(START_DATE) =10
GROUP BY CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
ORDER BY CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID DESC
