-- 코드를 입력하세요
SELECT A2.CATEGORY,A2.PRICE AS MAX_PRICE, A2.PRODUCT_NAME
FROM(
SELECT *
FROM FOOD_PRODUCT
HAVING CATEGORY = '국' OR  CATEGORY = '김치' OR  CATEGORY = '식용유' OR CATEGORY='과자'
ORDER BY PRICE DESC) A2
GROUP BY A2.CATEGORY
ORDER BY A2.PRICE DESC